Cargo.toml
benches/recursive-snark-supernova.rs
src/bellpepper/mod.rs
src/bellpepper/r1cs.rs
src/circuit.rs
src/gadgets/ecc.rs
src/lib.rs
src/nifs.rs
src/spartan/direct.rs
src/supernova/mod.rs
src/supernova/test.rs
src/traits/mod.rs

This PR removes the `supernova` feature, since we will make it available unconditionally.  It also contains some minor stylistic (naming) changes.

Remove supernova feature

---

benches/compressed-snark.rs
benches/compute-digest.rs
benches/recursive-snark-supernova.rs
benches/recursive-snark.rs
benches/sha256.rs
examples/minroot.rs
examples/minroot_serde.rs
src/bellpepper/mod.rs
src/bellpepper/r1cs.rs
src/circuit.rs
src/gadgets/ecc.rs
src/lib.rs
src/nifs.rs
src/provider/pedersen.rs
src/r1cs.rs
src/spartan/direct.rs
src/spartan/ppsnark.rs
src/supernova/mod.rs
src/supernova/test.rs
src/traits/commitment.rs
src/traits/snark.rs

This reduces the size of public parameters by ~2 when a "classic" SNARK is used.
This is a port of https://github.com/microsoft/Nova/pull/203

feat: Make commitment key generation configurable with an optional parameter

---

src/circuit.rs
src/lib.rs
src/nifs.rs
src/provider/poseidon.rs
src/supernova/mod.rs
src/supernova/test.rs
src/traits/mod.rs
src/traits/snark.rs

- makes RO traits a tad more approachable by removing the `ROConstants` trait, 
- removes `Sized` bounds (on `Group`, which is used as a generic parameters, they are redundant)

Small RO trait simplification

---

benches/recursive-snark-supernova.rs
src/lib.rs
src/r1cs.rs
src/supernova/mod.rs
src/supernova/test.rs
src/traits/circuit_supernova.rs

This PR contains some small initial refactoring of the SuperNova tests, mostly intended to help expose the shape of the problem and remove some noise:
- Compute commitment key based on max shape separately for primary/secondary.
- Consider key size based on max of constraints and inputs (not just constraints).
- Move commitment key computation into the library.
- Use `set_commitment_key` rather than more verbose manual equivalent.
- Remove unneeded `gen_commitment_key_by_r1cs`.
- Various minor renames.

Refactor supernova tests

---

benches/recursive-snark-supernova.rs
src/supernova/circuit.rs
src/supernova/mod.rs
src/supernova/test.rs
src/traits/circuit_supernova.rs

This PR tries to tease apart usages of the supernova `TrivialTestCircuit`:
- create a new `TrivialSecondaryCircuit` for use in NIVC generally.
- leave the existing test circuit, but remove references to ROM.
- modify uses of program counter on the secondary circuit from the NIVC mechanism, so secondary circuits are not required to provide it
- add some initial support for `CircuitSet` type to formalize what an NIVC user will need to provide
I think it may be possible (and if so, probably desirable) to just use a normal trivial `StepCircuit` (not supernova) for the secondary circuit. However, trying to do this maximally led me into problems I could not debug. Hopefully as the implementation undergoes ongoing crypto review and refactoring/extension it will become clear which parts of the …

clean up secondary circuit

---

src/supernova/mod.rs
src/supernova/test.rs

This PR defines a `NonUniformCircuit` trait which manages most of the complexity of driving NIVC. Applications can provide an implementation of this trait then create proofs as shown in the existing (now refactored) test.

Refactor to use NonUniformCircuit.

---

Cargo.toml
src/lib.rs
src/nifs.rs
src/provider/pasta.rs
src/r1cs.rs
src/spartan/ppsnark.rs
src/spartan/snark.rs
src/supernova/mod.rs

This PR is the next-in-line from downstream PR from https://github.com/lurk-lab/lurk-rs/pull/627, implementing an unified tracing ecosystem. Additionally, we add the `tracing_texray` crate, with allows us to easily visualize spans and benchmarks of lurk. Texray can be enabled wherever and [tracing](https://crates.io/crates/tracing) offers a lot of flexibility; please see the documentation for more info ([tracing-texray](https://crates.io/crates/tracing-texray)).
With this, we can get nice mirco-benchmarks like this:
```
RecursiveSNARK::prove_step                   219ms               ├────────────┤
<MultiFrame as StepCircuit>::synthesize     38ms                ├─┤
<_ as Group>::vartime_multiscalar_mul       50ms                  ├─┤
NIFS::prove                                106ms …
```

Standardize `tracing` crate + implement micro-benchmarking

---

benches/compressed-snark.rs
benches/recursive-snark-supernova.rs
benches/recursive-snark.rs
benches/sha256.rs
examples/minroot.rs
examples/minroot_serde.rs
src/digest.rs
src/errors.rs
src/lib.rs
src/spartan/ppsnark.rs
src/spartan/snark.rs
src/supernova/mod.rs
src/supernova/test.rs

- Refactored `src/digest.rs` to replace `Vec<u8>` storage with dedicated Write I/O.
- Removed optional `hasher` and introduced dedicated factory method.
- Reworked digest computation and mapping into separate functions.
- Merged build and digest computation to enhance coherence.
- Improved type safety with Result error propagation.

refactor: Refactor DigestBuilder

---

Cargo.toml
src/gadgets/utils.rs
src/supernova/circuit.rs
src/supernova/mod.rs
src/supernova/test.rs
src/traits/circuit_supernova.rs

This PR formalizes the requirement that the new program counter returned from `circuit_supernova::StepCircuit::synthesize()` is the one assigned to the circuit that is actually synthesized at each step.
The previous `TestROM` example actually did *not* follow this convention but rather used the program counter for its own purposes, as an index into a predetermined sequence of operations — then enforced the correctness of this ad-hoc indexing scheme in each circuit.
The current work enforces the constraint that `pc` has been correctly calculated and returned from each circuit, requiring that it is interpreted precisely as that circuit's assigned index in the `RunningClaim`s.
In order to make the existing tests pass, they were reworked to re-envision the pseudo-pc enforcement at the start …

Enforce program counter in SuperNova StepCircuit.

---

.github/workflows/bench_pr_comment.yml

Enables the `dorny/paths-filter` action to properly detect changes from the PR branch

fix: Detect source changes in PR branch correctly

---

benches/compressed-snark.rs
benches/recursive-snark-supernova.rs
benches/recursive-snark.rs
benches/sha256.rs
examples/minroot.rs
examples/minroot_serde.rs
src/digest.rs
src/errors.rs
src/lib.rs
src/spartan/ppsnark.rs
src/spartan/snark.rs
src/supernova/mod.rs
src/supernova/test.rs

This PR implements a `DigestBuilder` and supplementary traits:
- `HasDigest`
- `Digestible`
- `SimpleDigestible`
Some elements of this PR are intended to support #31 (see #34) and #29. The goal is to begin work on a framework that will rationalize digest creation, at least across existing use cases and those in the linked issues. The present work moves us in that direction while maintaining the status quo by not affecting the values of existing digests.
Some details of the requirements implied by #29 and #31 will likely require further refactoring, but that will best be done in the context of that work rather than here. I mention this mainly to explain that the current PR is still somewhat rough and has some loose ends that will either need to be tightened up or removed later.

Add DigestBuilder.

---

src/supernova/circuit.rs
src/supernova/mod.rs

This will be needed for fast parameter loading for SuperNova.

Derive Abomonation for SuperNova PublicParams.

---

.github/workflows/bench_pr_comment.yml

Currently the `!benchmark` comment action takes over an hour on some runs while testing:
- `ubuntu-latest`: https://github.com/samuelburnham/arecibo/actions/runs/6152060907
- `self-hosted`: https://github.com/samuelburnham/arecibo/actions/runs/6154107492
This PR switches to an 8-core, 32GB RAM cloud-hosted runner that will autoscale up to 50 concurrent tasks, each with their own machine. Unfortunately it is impossible to test on forks, but it will likely be significantly faster than `ubuntu-latest` (2-core, 7GB RAM) and will save money versus running on self-hosted infra.

ci: Switch `!benchmark` action to larger cloud-hosted runners

---

benches/recursive-snark-supernova.rs
src/supernova/mod.rs
src/supernova/test.rs

The initial SuperNova implementation diverged from Nova's pattern for non-deterministic step proofs — by saving a prototype circuit in the `RunningClaim` then reusing it with new 'public' inputs at each step. However, since each step's computation may depend on non-deterministic private inputs, `prove_step` actually needs to receive an instance of the primary circuit per-step.
This PR accomplishes that but continues to use the previous method for the secondary circuit, on the theory that the approach to NIVC implemented and supported here assumes and requires that a trivial deterministic function will be proved in the secondary circuit.
Because downstream work depends on this change, this PR is a minimal patch. Future work should add a test modeled on the equivalent Nova test, exercising …

Support non-determinism in NIVC circuits.

---

Cargo.toml
examples/minroot.rs
src/bellpepper/r1cs.rs
src/lib.rs
src/nifs.rs
src/r1cs/mod.rs
src/r1cs/sparse.rs
src/r1cs/util.rs
src/spartan/ppsnark.rs
src/spartan/snark.rs

Resolves #37.
This PR implements CSR matrix-vector multiplication under the `"csr"` feature. (This was for me to debug; if CSR sould become the only representation, then we can simply replace and remove the feature.) We get a slight uptick in performance, around 10%.
Notes:
There are many sparse matrix crates available in rust. However, most of these crates are do not parallelize, or are not compatiable with field elements. For example, [sprs](https://crates.io/crates/sprs/0.2.1) does not parallelize its sparse matrix / dense vector multiplication. It's traits also require `num_traits::Zero`, which is not compatiable with `ff::PrimeField`.
CSR:
```
Nova-based VDF with MinRoot delay function
=========================================================
Proving 1 iterations of MinRoot per step …
```

CSR Representation for Sparse Matrices

---

src/supernova/mod.rs

This PR removes the `mut` on the `&self` parameter in SuperNova's `verify()`. This is needed for https://github.com/lurk-lab/lurk-rs/pull/677.

Self can be immutable.

---

Cargo.toml
benches/compressed-snark.rs
benches/compute-digest.rs
benches/recursive-snark-supernova.rs
benches/recursive-snark.rs
benches/sha256.rs
examples/minroot.rs
examples/minroot_serde.rs
src/digest.rs
src/lib.rs
src/r1cs/mod.rs
src/spartan/ppsnark.rs
src/spartan/snark.rs
src/supernova/mod.rs
src/supernova/test.rs

- refactors the `DigestBuilder` introduced in #40 to something that sets aside the builder pattern, but is hopefully simpler: having an unambiguous transient `DigestComputer` that is effectively taking the (configurable) `Digestible` bytes, and computing a digest from it
- stores and caches this digest in the structure in a way that is then not polluting the `Digestible` bytes, even for a struct that implements `SimpleDigest`. The cache also 1/ can't be populated twice, 2/ can't be befuddled by structs deserialized from incorrect digest information.
- this applies this pattern to add a (cached) digest to `R1CSShape`, which is orthogonal to the digest of public parameters.
- embed the digest of `R1CSShape`s constituent of `PublicParameters` inside their `Digestible` bytes, since [as …

feat: add a digest to R1CSShape

---

src/supernova/error.rs
src/supernova/mod.rs

- Integrated #[from] attribute in `SuperNovaError` for efficient use of `NovaError`.
- Consolidated call sites to use the conversion.

refactor: Simplify error type in SuperNova module

---

src/lib.rs

Generic type aliases are type functions. In our case, they are made distinct through the arguments they are passed, not by giving them different names.

refactor: simplify type aliases in tests

---

benches/recursive-snark-supernova.rs
src/constants.rs
src/lib.rs
src/nifs.rs
src/provider/pasta.rs
src/r1cs/mod.rs
src/r1cs/sparse.rs
src/supernova/mod.rs
src/supernova/test.rs

We split out the `PublicParams` within each `RunningClaim` into a new `supernova::PublicParams`. This split prepares for downstream changes in lurk-rs (https://github.com/lurk-lab/lurk-rs/pull/648) to working with the public parameter infra. 
- We aggregate the common primary commitment key and any other shared information amongst all the params into the main `PublicParams` structure and create a new `CircuitShape` structure to manage per-circuit parameters. 
- We mirror the Nova API and modify the supernova `prove`/`verify` functions to take a public params, as well as computing digests.
- We remove `RunningClaims`, which ends being a glorified `usize`.
Closes #29

Setup SuperNova public parameter infrastructure

---

src/lib.rs

[microsoft/171](https://github.com/microsoft/Nova/pull/171) introduced enhanced genericity in tests to facilitate unit testing across diverse curve cycles.  Since then, the lib.rs tests, being designed to verify certain behaviors of the decider SNARK, tend to embed the use of a RelaxedR1CSSnark<G, EE>. They do this under the alias (where the test carefully chooses a specific import path for RelaxedR1CSSnark):
```rust
type S1<G> = RelaxedR1CSSnark<G, ipa_pc::EvaluationEgine<G>>
```
Effectively, this constrains the PCS utilized by that decider to the IPA, even if the only thing the test function needed to be specific about is `RelaxedR1CSSnark`.
Hence, these generic tests then had to accommodate constraints facilitating the use of the IPA, specifically:
```rust
<G::CE as …
```

refactor: Parametrization of lib.rs tests for various EvaluationEngines

---

src/supernova/mod.rs

This PR addresses #68 (and is the arecibo fix of issue [#695](https://github.com/lurk-lab/lurk-rs/issues/695) in lurk-rs)
The only change is we return `zi_primary` and `zi_secondary` in `supernova::RecursiveSNARK::verify` to match what's done in [`RecursiveSNARK::verify`](https://github.com/lurk-lab/arecibo/blob/c657b04a005182cb7bc1937f22b70dde747c1bdc/src/lib.rs#L532)

Adjust `supernova::RecursiveSNARK::verify` API

---

.github/workflows/rust.yml

#48 tests seem to be bottlenecked on hardware, so this PR upgrades from the stock GitHub runner (2 vCPUs, 7GB RAM) to Buildjet (8 vCPUs, 32GB RAM).
Note: Adding Buildjet to a repo also requires going to organization Settings->GitHub Apps->Buildjet-Configure and granting access to the repo.

Upgrade to Buildjet runner with 8 CPUs

---

src/provider/pedersen.rs
src/r1cs/sparse.rs

Further work from https://github.com/lurk-lab/lurk-rs/pull/777.
This continues the story. pq observes that:
> I now believe, based on informal observation, that the loading in mmap-fix is slower than generating fresh params.
The long loading times were due to two separate issues. The first is a bug (fixed in https://github.com/lurk-lab/lurk-rs/pull/777), and the second is the lack of parallelization. This PR addresses the low hanging fruit by implementing parallel clones for the large data structures. We see ~2x speedup.
Before this PR:
```
bang!                                         24.328472s ├─────────────────────────────────────────────────────────────┤
Instance::new                                535.148ms │
<MultiFrame as StepCircuit>::synthesize     230.39ms  │
read_abomonated …
```

chore: Parallel clones for large data structures

---

src/lib.rs
src/r1cs/mod.rs
src/spartan/direct.rs
src/spartan/ppsnark.rs
src/spartan/snark.rs
src/traits/snark.rs

As explained by @zaverucha in https://github.com/microsoft/Spartan2/pull/2 (with edits for precision):
The `R1CSShape` object was being stored in both:
- the `ProverKey` of the `spartan::direct::DirectSNARK`, which generically employs any instance of `RelaxedR1CSSNARKTrait`,
- the `ProverKey` of each of the two `RelaxedR1CSSNARKTrait` implementations in `spartan::{snark, ppsnark}::RelaxedR1CSSNARK`,
- the `PublicParams` that are passed to the proof method of `crate::CompressedSNARK<G1, G2, C1, C2, S1, S2>`, which generically employs any instance of `RelaxedR1CSSNARKTrait`.
IOW, `RelaxedR1CSSNARKTrait` is always accessed through generic structs (`DirectSNARK`, `CompressedSNARK`) which already have a copy of the relevant `R1CSShape`. We store it once in the top level object (`DirectSNARK`'s …

fix: remove a duplicate `R1CSShape` in the `RelaxedR1CSSNARK`'s chosen `ProverKey`

---

Cargo.toml
ThirdPartyNotices.txt
examples/minroot_serde.rs
src/lib.rs
src/provider/bn256_grumpkin.rs
src/provider/kzg_commitment.rs
src/provider/mod.rs
src/provider/non_hiding_kzg.rs
src/provider/non_hiding_zeromorph.rs
src/spartan/direct.rs
src/spartan/polys/multilinear.rs
src/spartan/polys/univariate.rs
src/supernova/test.rs

- makes tests generic in the `EvaluationEngine` by adopting #70,
- documents the gap between ZM / IPA: "endianness" w/ which coefficients must be supplied to the scheme,
- implements a `CommitmentKey` with a token universal setup, which allows implementing a `CommitmentEngineTrait` for KZG commitments,
- implements the prove & verify methods for the `EvaluationEngineTrait` implementation for ZMPCS. The scheme is slow (due to poor univariate KZG batching) 
Closes #19 
TODO: 
Next steps:
- making univariate KZG actually fast,
- document the protocol a bit more #35, 
- #22,

Zeromorph EvaluationEngine trait

---

.github/workflows/rust.yml

- Introduced a GitHub Action job `check-lurk-compiles` to verify the compilation of `lurk-rs` types.
- Implementation involved checking out two repositories, patching `Cargo.toml` in `lurk`, and conducting `cargo check` with different flags.
Checked: the [test run](https://github.com/lurk-lab/arecibo/actions/runs/6667665254) does print
```
Checking nova-snark v0.24.0 (/home/runner/actions-runner/_work/arecibo/arecibo/arecibo)
```

ci: Implement GitHub action to check 'lurk-rs' compilation

---

Cargo.toml
benches/compressed-snark.rs
benches/recursive-snark-supernova.rs
benches/recursive-snark.rs
benches/sha256.rs
examples/minroot.rs
src/lib.rs
src/supernova/mod.rs
src/supernova/test.rs

Ports https://github.com/microsoft/Nova/pull/238 and https://github.com/microsoft/Nova/pull/242 (squashed together, as part of #242 reverts part of #238).
TL;DR, `z0` no longer needs to be provided to Nova on every `prove_step`, and the creation of the `RecursiveSNARK` copies a set of `z0_{primary, secondary}` passed by reference. This is expected to require adjustment in Lurk.
I added one commit for the SuperNova adjustments.

Update the RecursiveSNARK API (Nova forward port)

---

benches/recursive-snark-supernova.rs
src/supernova/mod.rs
src/supernova/test.rs
src/traits/circuit_supernova.rs

This PR adds a test exercising support for non-deterministic hints in NIVC. It is based on the equivalent test for IVC in Nova. Instead of proving a series of sequential fifth-root computations (which would be expensive to calculate directly, so instead are calculated in reverse to produce the sequence of hints) — we produce a sequence of alternating cube and fifth roots. This alternation exercises NIVC. We hardcode the next program-counter into the circuit, so that alternation is enforce.
The other changes are fixing typos in the code ('unifrom' -> 'uniform') and removing the default implementation of `circuit_index` for `circuit_supernova::StepCircuit` — which proved error-prone (confirming a suggestion @arthurpaulino made previously).
TODO:
- Add a test of compression once the NIVC …

Add non-deterministic ivc test.

---

benches/compressed-snark.rs
benches/compute-digest.rs
benches/recursive-snark-supernova.rs
benches/recursive-snark.rs
benches/sha256.rs
examples/minroot.rs
examples/minroot_serde.rs
src/bellpepper/mod.rs
src/bellpepper/r1cs.rs
src/circuit.rs
src/gadgets/ecc.rs
src/lib.rs
src/nifs.rs
src/r1cs/mod.rs
src/spartan/direct.rs
src/supernova/mod.rs
src/supernova/test.rs
src/traits/snark.rs

See #5 and https://github.com/microsoft/Nova/pull/203, by which public parameter creation takes a size hint. This size hint carries the particular requirements of the final compressing SNARK the user expected to use with these public parameters.
This avoids setting the size of public parameters too conservatively for all users of the code base, but rather limits the use of "big" public parameters to those constructions that will eventually need them.
We slightly simplify the API of passing a commitment key size hint when creating public parameters. We apply this to Supernova, closing #53.
Companion Lurk PR at https://github.com/lurk-lab/lurk-rs/pull/843
- Converted `CommitmentKeyHint<G>` from a boxed dynamic trait object to a direct dynamic trait object in `r1cs/mod.rs`.
- Changed the …

refactor: Refactor public parameters setup to remove optionality of commitment key size hint

---

Cargo.toml
src/bellpepper/mod.rs
src/circuit.rs
src/errors.rs
src/gadgets/ecc.rs
src/gadgets/nonnative/bignat.rs
src/gadgets/nonnative/util.rs
src/gadgets/r1cs.rs
src/gadgets/utils.rs
src/lib.rs
src/nifs.rs
src/provider/ipa_pc.rs
src/provider/mod.rs
src/provider/poseidon.rs
src/r1cs/mod.rs
src/spartan/direct.rs
src/spartan/mod.rs
src/spartan/polys/identity.rs
src/spartan/polys/mod.rs
src/spartan/polys/power.rs
src/spartan/ppsnark.rs
src/spartan/snark.rs
src/spartan/sumcheck.rs
src/supernova/circuit.rs
src/supernova/test.rs
src/traits/snark.rs

Closes #88. Ports the following from upstream:
- https://github.com/microsoft/Nova/pull/240 
- https://github.com/microsoft/Nova/pull/243
- https://github.com/microsoft/Nova/pull/245
- https://github.com/microsoft/Nova/pull/246
- https://github.com/microsoft/Nova/pull/247
- https://github.com/microsoft/Nova/pull/248
- https://github.com/microsoft/Nova/pull/250
<details>
<summary> CPU Bench results for https://github.com/microsoft/Nova/pull/240 </summary>
```
group                                                        main                                   nova_240
-----                                                        ----                                   --------
CompressedSNARK-Commitments-StepCircuitSize-0/Prove          1.00       7.5±0.05s            1.00       7.5±0.11s …
```

Forward ports from Nova (easy)

---

src/gadgets/utils.rs
src/r1cs/mod.rs
src/supernova/circuit.rs
src/supernova/test.rs
src/supernova/utils.rs

This PR fixes #94. I think the alternate approach (checking consistency of the chosen and received target index) is probably a little better. I may take a shot at this along with investigating a refactoring to avoid duplication of the bit-checking, etc. in a separate PR. Meanwhile, this should fix the immediate issue straightforwardly.

Ensure exactly one selection in get_from_vec_alloc_relaxed_r1cs.

---

src/provider/kzg_commitment.rs
src/provider/mod.rs
src/provider/non_hiding_kzg.rs
src/provider/non_hiding_zeromorph.rs
src/provider/util.rs
src/provider/util/fb_msm.rs
src/provider/util/mod.rs
src/supernova/test.rs

- Introduced a new module `util` within the `provider` module, implementing fixed-base MSM,
- properly expressed the KZG SRS generation as an MSM,
- New trait constraint has been imposed for `E::Fr: PrimeFieldBits` within the `non_hiding_zeromorph.rs` file, and usages have been adjusted in the `test` module.
- Adding the `PrimeFieldBits` import from the `ff` crate and importing `provider::util` from the local crate.
<details>
<summary> Result of running the tests before / after </summary>
```
nova-snark bellpepper::tests::test_alloc_bit: Before = 0.052s, After = 0.068s
nova-snark circuit::tests::test_recursive_circuit_grumpkin: Before = 37.498s, After = 4.36s
nova-snark circuit::tests::test_recursive_circuit_pasta: Before = 1.579s, After = 2.124s
nova-snark …
```

feat: Enhance KZG commitment SRS generation efficiency 

---

benches/recursive-snark-supernova.rs
src/supernova/mod.rs
src/supernova/test.rs

Closes #63 & #64.
This PR simplifes the SuperNova API by:
- renaming `iter_base_step` to `new`
- minimize args to `supernova::RecursiveSnark::new` — almost matching those of `nova::RecursiveSnark::new`.
- (The remaining extra arg is new — NonUniformCircuit, which helps derive removed args but cannot itself be eliminated.)
- minimize args to `supernova::RecursiveArgs::prove_step` — matching those of `nova::RecursiveSnark::prove_step`.

Simplify api

---

.github/workflows/rust.yml

- Modified the Rust GitHub action workflow by removing the `push` event type.
- Introduced a conditional execution check to the `check-lurk-compiles` job, which now only triggers for `pull_request` events.
- Closes #103.

ci: refine triggers for Rust tests

---

Cargo.toml

This is fully expected to break on CI, but the full setup was tested locally.
> [!WARNING]  
> Sequencing for this PR:
> ~~1. companion Lurk PR is open ([#869](https://github.com/lurk-lab/lurk-rs/pull/869))~~
> 2. this PR is reviewed ✅ despite CI status being ❎ 
> 3. https://github.com/lurk-lab/neptune/tree/dev is reset to https://github.com/lurk-lab/neptune/tree/dev_ng
> 4. this PR's CI is re-run and succeeds
> 5. this PR is merged
> [!NOTE]
> If you want to test this at home:
> 1. checkout https://github.com/lurk-lab/neptune/tree/dev_ng (note the specific branch) to $FOO/neptune
> 2. change the neptune dependency in *this* repo to `neptune = { path="$FOO/neptune", default-features = false, features = ["abomonation"] }`
> 3. run tests as usual

chore: switch to abomonation_derive_ng

---

.github/workflows/bench_pr_comment.yml

Now that Buildjet has been battle tested for a few weeks, the GitHub-hosted larger runners are removed to simplify the org-wide runner config.

chore: switch PR bench runners to Buildjet

---

src/supernova/circuit.rs
src/supernova/test.rs

Avoid recreating default R1CS instance

---

src/spartan/ppsnark.rs
src/spartan/snark.rs

This PR factor's out the 3rd Sumcheck instance in `snark.rs`so that it can be used in the upcoming batched compressed SNARK work.

`snark.rs`: factor out batch evaluation Sumcheck

---

src/supernova/mod.rs

This PR makes some small changes to the `RecursiveSNARK` struct.
- Ensures that synthesizing the circuit during public parameter generation does not fail.
- Document fields of `RelaxedSNARK`
- Convert `r_W_secondary` and `r_U_secondary` from `Vec<Option<T>>` to `T` since we are always only folding a single circuit on the secondary curve.

SuperNova: clean-up `RecursiveSNARK`

---

src/errors.rs
src/lib.rs
src/provider/ipa_pc.rs
src/provider/mod.rs
src/r1cs/mod.rs
src/spartan/ppsnark.rs

Ports:
- last commit from https://github.com/microsoft/Nova/pull/203 (everything else was there already)
- https://github.com/microsoft/Nova/pull/254

More Nova forward ports

---

src/supernova/mod.rs

This PR fixes some issues with `supernova::RecursiveSNARK::verify`:
- Previously, only the last folded primary circuit's instance was being verified. We now verify all all instances
- For circuits which have not been executed, the wrong public parameters were being used to generate a default `RelaxedR1CSInstance` to be hashed into the RO.
- Added extra sanity checks

SuperNova: Improved `RecursiveSNARK::verify`

---

Cargo.toml
src/bellpepper/r1cs.rs
src/nifs.rs
src/r1cs/mod.rs

- Added a new dependency `vecshard` version "0.2.1" in the Cargo.toml file.
- Updated `NovaWitness` trait method `r1cs_instance_and_witness` to consume self, impacting its implementation in `SatisfyingAssignment`.
- Replaced slicing operations with in-place split for `input_assignment` using `ShardExt` trait.
- Removed unnecessary variable references in `R1CSWitness::new` and `R1CSInstance::new` function calls.
- Refactored `new` methods in `R1CSWitness` and `R1CSInstance` to accept `Vec` instead of a slice, and removed redundant `.to_owned()` operation.
This offers one possible alternative for some of the changes in #118

refactor: Refactor R1CS for in-place operations and Vec inputs

---

Cargo.toml
src/bellpepper/r1cs.rs
src/nifs.rs
src/r1cs/mod.rs

This reverts commit fdf82964533186e701784b3128897df031c080e1.
This should allow us to investigate the effects of components of https://github.com/lurk-lab/arecibo/pull/118 without noise. We can re-apply this later if we see it as an improvement.

Revert "refactor: Refactor R1CS for in-place operations and Vec inputs (#121)"

---

src/gadgets/utils.rs
src/supernova/circuit.rs
src/supernova/mod.rs
src/supernova/test.rs
src/supernova/utils.rs
src/traits/circuit_supernova.rs

This PR fixes some minor annoyances in the SuperNova circuit and adds documentation.
- Compute number of RO inputs for public output via a function
- Compute instance selector vector from `last_augmented_circuit_index` in `alloc_witness`
- Reuse the selector across the base and non-base branches.
- Add comments

SuperNova: Improve circuit

---

src/gadgets/utils.rs
src/supernova/test.rs
src/supernova/utils.rs

The ROM test was broken and not actually doing what it was supposed to. 
In particular:
- The input rom_index was initialized with the first opcode, rather than 0
- `SquareCircuit::synthesize` was checking the next opcode twice
- `constrain_augmented_circuit_index` was not checking what it was supposed to.
This issue was found while trying to remove dead code in PR #120.

SuperNova: Fix ROM test and remove dead code

---

src/r1cs/mod.rs
src/r1cs/sparse.rs

Addresses #137.
This PR refactors the `R1CSShape` sparse matrix / dense vector multiplication API to avoid the unnecessary cloning and allocating of memory. In the codebase, we often see the pattern:
```rust
let z = [W.W.clone(), vec![U.u], U.X.clone()].concat();
let (Az, Bz, Cz) = self.multiply_vec(&z)?;
```
This is memory-inefficient. The new API directly uses references to the witness vectors, like this:
```rust
let (Az, Bz, Cz) = self.multiply_witness(&W.W, &U.u, &U.X)?;
```
Benchmark results from downstream `lurk-rs` confirm that this improves performance: https://github.com/lurk-lab/lurk-rs/pull/923
<details>
<summary>Click to view benchmark</summary>
| Test | Base         | PR               | % |
|------|--------------|------------------|---|
| LEM Fibonacci Prove - rc = …

Reduce allocations/cloning in spmvm

---

Cargo.toml
src/spartan/batched.rs
src/spartan/mod.rs
src/spartan/polys/multilinear.rs
src/spartan/snark.rs
src/spartan/sumcheck.rs
src/supernova/snark.rs

- Rework all batched Sumcheck provers to handle instances of different sizes
- Add `SumcheckProof::verify_batch` to handle scaling. 
- Improve `batch_verify` of MLE evaluations to also handle different sized claims -> should help existing SNARK as well.

Fix Batched SNARK

---

Cargo.toml
src/provider/non_hiding_zeromorph.rs
src/spartan/polys/univariate.rs

Tests & documents Zeromorph.
Most tests inspired / adapted from the equivalent ones in the Aztec PR. Our 3d-party notices amended accordingly.
> [!NOTE]
> Lurk isn't expected to compile on the Zeromorph branch.
Closes #35

Finish documenting / testing Zeromorph

---

src/bellpepper/r1cs.rs
src/lib.rs
src/nifs.rs
src/r1cs/mod.rs
src/spartan/direct.rs
src/supernova/mod.rs

Addresses #137 and replaces #138.
This PR uses the new API in `WitnessCS` to preallocate the witness buffers before calling `synthesize`. This ensures that we do not unnecessarily grow and reallocate these large witness buffers, which adds overhead.

Preallocate witness before synthesis

---

.clippy.toml
Cargo.toml
src/gadgets/nonnative/bignat.rs
src/gadgets/r1cs.rs
src/gadgets/utils.rs
src/provider/ipa_pc.rs
src/provider/mod.rs
src/provider/msm.rs
src/r1cs/mod.rs
src/r1cs/sparse.rs
src/spartan/mod.rs
src/spartan/polys/eq.rs
src/spartan/polys/multilinear.rs
src/spartan/ppsnark.rs
src/spartan/snark.rs
src/spartan/sumcheck.rs
src/supernova/circuit.rs
src/supernova/mod.rs
src/supernova/test.rs
src/supernova/utils.rs

We very often use the zip combinator for iterators (often computed over a vector) in order to set up a computation loop. Typically:
```rust
A_vec.into_par_iter().zip(B_vec.par_iter()).map(|(a, b)| foo(a, b)).collect::<Vec<_>>()
```
We very often mean for `A_vec` and `B_vec` to have exactly the same size, but the construction above will not actually check that, as `zip` returns an iterator that will yield as many pairs as the length of the smaller iterator between A and B.
In order to make sure we aren't bitten by a missing length check, this replaces zip with iterators that panic if the length of their arguments are unequal. 
- Replaced `.zip` method with `.zip_eq` from Itertools across multiple files to ensure equal length iteration between zipped arrays,
- Updated the clippy …

refactor: Replace zip with zip_eq for iterator safety

---

src/spartan/batched.rs
src/spartan/batched_ppsnark.rs
src/spartan/mod.rs
src/spartan/polys/eq.rs
src/spartan/polys/power.rs

Don't create all the powers for every `PowPolynomial` when batching. Instead create all the powers once and copy the ones needed. Also, don't even make the `PowPolynomial` (cloning all the powers), when only doing so to get the evals.
This may not matter much, since I guess the concrete number of powers grows logarithmically so may be smallish. Nevertheless, if we aspire to very large circuit sets, it may be worth thinking this way.

Only create taus once.

---

src/lib.rs
src/nifs.rs
src/r1cs/mod.rs
src/r1cs/sparse.rs

Addresses #137.
This PR addresses the cloning/allocation of large vectors used in the intermediary steps of each Nova `prove_step` computation. In particular, we focus on `NIFS::prove`, which allocates new vectors to compute the fold step, when technically we could be reusing and overwriting the already allocated vectors from the previous step. Concretely, we add the functions `NIFS::prove_mut` and `R1CSRelaxedWitness/Instance::prove_mut`. We also add a `ResourceSink` with preallocated buffers for `ABC_Z{1,2}` and `T`s to help as stratch memory for the `commit_T_into` operation.

Remove large vector allocations

---

src/spartan/batched_ppsnark.rs
src/spartan/polys/multilinear.rs
src/spartan/ppsnark.rs
src/spartan/snark.rs
src/supernova/circuit.rs

Absolute visibility modifiers tend to not inadvertently make things public when you move code, contrarily to (super).
- Changed the visibility scope of several fields and methods within multiple substrates in the `ppsnark.rs` file to be within the `crate::spartan`.
- Altered the module import path in the `circuit.rs` file from `super` to `crate::supernova`.
- Modified the visibility of the `WitnessBoundSumcheck` in `batched_ppsnark.rs`, the visibility scope is now set to `crate::spartan`.
- Scoped `batch_eval_prove` and `batch_eval_verify` functions within `crate::spartan` in `snark.rs`.

Refactor: use pub(in crate::foo) rather than pub(super)

---

src/provider/ipa_pc.rs
src/spartan/batched.rs
src/spartan/batched_ppsnark.rs
src/spartan/polys/eq.rs
src/spartan/polys/multilinear.rs
src/spartan/polys/power.rs
src/spartan/snark.rs

This eliminates some unnecessary cloning caused by unused intermediate `EqPolynomial`s.

Avoid EqPolynomial when only for evals.

---

src/spartan/batched_ppsnark.rs
src/spartan/macros.rs
src/spartan/sumcheck.rs

The base branch (`batched_spartan`) was broken by this (squashed) commit of #158: https://github.com/lurk-lab/arecibo/pull/158/commits/1ced24b1e610b1a53b94a15c931275e27a88f217.
It had effectively replaced instances of `foo.for_each(…)` with `let _ = foo.map(…)`. However, these are not equivalent since `map` creates an iterator which may have no effect if not consumed. While we *could* do something like `let _ = foo.map(…).count()` to force side effects to manifest, this is brittle and works against the goal of removing the cognitive burden of incidental plumbing in these pipelines.
For that reason, I'm simply reverting the changes that broke the test that led to discovering this.

Restore zip_with_for_each.

---

src/spartan/batched.rs
src/spartan/batched_ppsnark.rs
src/spartan/macros.rs
src/spartan/mod.rs
src/spartan/polys/multilinear.rs
src/spartan/sumcheck.rs
src/supernova/mod.rs
src/supernova/snark.rs
src/supernova/test.rs
src/traits/snark.rs

The current macro system requires learning what 7 auxiliary macros do: `zip_with, zip_with_for_each, zip_with_into_par_iter, zip_with_iter, zip_with_par_iter, zip_with_par_iter_mut_for_each, zip_with_into_iter`.
Switches us to a mode in which the user has only 2 macros to learn about : `zip_with` and `zip_with_for_each`.
This further documents them as such:
```
// no iterator projection specified: the macro assumes the arguments *are* iterators
// zip_with!((iter1, iter2, iter3), |a, b, c| a + b + c) -> iter1.zip_eq(iter2.zip_eq(iter3)).map(|(a, (b, c))| a + b + c)
//
// iterator projection specified: use it on each argument
// zip_with!(par_iter, (vec1, vec2, vec3), |a, b, c| a + b + c) -> 
// vec1.par_iter().zip_eq(vec2.par_iter().zip_eq(vec3.par_iter())).map(|(a, (b, c))| a + b + c) …
```

Streamline macro syntax

---

src/supernova/snark.rs

This PR:
* cleans up `supernova::CompressedSNARK` by deleting some code duplication
* adds some annotations on the various steps of `prove` and `verify`
* fixes some documentation typos
* Deletes an extra TODO
Ideally the `field_as_usize` function can get eliminated completely, but this could require some small changes to `supernova::RecursiveSNARK::verify`.

Documentation and code duplication in `supernova::CompressedSNARK`

---

benches/compressed-snark-supernova.rs
benches/recursive-snark-supernova.rs
src/supernova/mod.rs
src/supernova/snark.rs
src/supernova/test.rs

This PR removes the `circuit_index` dependence of `RecursiveSNARK::verify` that was being mis-used in the tests. Instead, we add a `proven_circuit_index` field in `RecursiveSNARK` itself which plays the role of `circuit_index` in the `verify` method.
The `proven_circuit_index` name was a random name I chose that seemed evocative, I'm open to changing it.
TODO before merge: 
~* Add a check that all the NIVC circuits for a particular instance have the same arity.~
~* Open a companion PR to `lurk-rs`~ Opened PR [lurk#951](https://github.com/lurk-lab/lurk-rs/pull/951)
Closes #64 
Closes #90

Remove circuit_index dependence of `supernova::RecursiveSNARK::verify`

---

.github/workflows/rust.yml
benches/compressed-snark-supernova.rs
benches/compressed-snark.rs
benches/recursive-snark-supernova.rs
benches/recursive-snark.rs
src/circuit.rs
src/supernova/circuit.rs

- avoids uneeded code duplication in benchmarks with auxiliary functions,
- update the circuit sizes used in Nova benchmarks to up-to-date values,
- creates very basic circuit sizing tests for Supernova and uses them in benchmarks,
Elements to be addressed after this PR:
- the Supernova circuit test only works for a num_augmented_circuit equal to 1, we'd like to test (at least) with 2 circuits ( https://github.com/lurk-lab/arecibo/issues/179 )
- we will probably need CI to track the values of this benchmark and publish fresh runs on gh-pages, similarly to https://github.com/lurk-lab/lurk-rs/blob/ab427f23a709e95edb656e6b29bd55f1e22424bc/.github/workflows/merge-tests.yml#L69-L205 ( https://github.com/lurk-lab/arecibo/issues/180)

fix: Improve benchmarks quality and code duplication 

---

Cargo.toml
LICENSE

This PR is the same change as in the patch release #188 — duplicated here for visibility on the default branch.

Add upstream to author/license for clarity.

---

.github/workflows/rust.yml
Cargo.toml

- Update the package name in the Lurk compilation check workflow.
- Upgrade to a newer Rust MSRV

ci: Update Rust version and correct package name in CI

---

src/spartan/polys/multilinear.rs

Forward ports small adjustments from https://github.com/microsoft/Nova/pull/281

Simplify ml evaluation testing (Nova Forward port, easy)

---

Cargo.toml
src/circuit.rs
src/lib.rs
src/supernova/circuit.rs

This closes #132. 
There may be other tests that would benefit from this (maybe the ecc op circuit tests for constraint numbers?)

Use `expect_test` in `test_pp_digest`, `test_recursive_circuit`, and `test_supernova_recursive_circuit`

---

src/supernova/Readme.md

This PR finishes up #181 by providing links and clears up trailing whitespace in the `supernova/Readme.md`.

Cleanup trailing whitespace and add documentation links

---

src/spartan/ppsnark.rs

This PR fixes https://github.com/lurk-lab/arecibo/issues/201.
It would be nice to apply the patch to [upstream](https://github.com/microsoft/Nova/tree/main) Nova implementation as well.

Removing redundant absorption to the transcript (#201)

---

src/provider/mlkzg.rs

This PR attempts to address @adr1anh 's comments from https://github.com/lurk-lab/arecibo/pull/172 , related to transcript absorptions. 
Fixes https://github.com/lurk-lab/arecibo/issues/202

chore: Remove redundant absorptions in MLKZG implementation

---

Cargo.toml
src/provider/bn256_grumpkin.rs
src/provider/pasta.rs

Resolves #186.
Note: `force-no-sort` does not disable sorting. It removes redundant sort-related symbols between `pasta-msm` and `grumpkin-msm` so the linker is happy.

GPU accelerated Grumpkin MSM

---

Cargo.toml
src/provider/bn256_grumpkin.rs
src/provider/kzg_commitment.rs
src/provider/mlkzg.rs
src/provider/mod.rs
src/provider/non_hiding_kzg.rs
src/provider/non_hiding_zeromorph.rs
src/provider/pasta.rs
src/provider/pedersen.rs
src/provider/secp_secq.rs
src/provider/traits.rs
src/provider/util/msm.rs

- makes src/provider group-crate aware and cleans corresponding redundancy,
- removes macro boilerplate created for #187

Clean up trait/macro boilerplate in provider

---

src/errors.rs
src/lib.rs
src/provider/non_hiding_zeromorph.rs
src/supernova/error.rs
src/supernova/mod.rs
src/supernova/utils.rs

Ports the following PRs from upstream Nova:
- https://github.com/microsoft/Nova/pull/285
- https://github.com/microsoft/Nova/pull/286
The second required some (relatively straightforward) adaptation in the port to SuperNova, please review.

Developer quality of life improvements (Nova forward ports)

---

src/provider/non_hiding_kzg.rs
src/provider/non_hiding_zeromorph.rs

Fixes https://github.com/lurk-lab/arecibo/issues/184
We exploit the fact that `batched_lifted_degree_quotient` ([link](https://github.com/lurk-lab/arecibo/blob/dev/src/provider/non_hiding_zeromorph.rs#L367)) computes `q_hat` with the first half of the coefficients equal to zero. During subsequent MSM computation in `UVKZGPCS::commit` ([link](https://github.com/lurk-lab/arecibo/blob/dev/src/provider/non_hiding_kzg.rs#L241)), zero coefficients of `q_hat`, which act as a scalars have no impact on the final value of 'UVKZGPCSCommitment'.
Two alternative implementations of `UVKZGPCS::commit` are actually proposed: 
- `UVKZGPCS::commit_offset` - uses additional offset that points to the first non-zero value among scalars (and same offset is used to skip non-relevant bases)
- …

Saving scalar multiplications while computing 'UVKZGPCSCommitment'

---

src/provider/mlkzg.rs

Fixes https://github.com/lurk-lab/arecibo/issues/229

Refactor 'kzg_verify_batch' closure in MLKZG verification

---

src/provider/mlkzg.rs

Fixes https://github.com/lurk-lab/arecibo/issues/232

Parallel computation of `Pi` polynomials

---

src/lib.rs
src/r1cs/mod.rs
src/supernova/mod.rs

Resolves the next step of #137.
This PR brings the changes done to the Nova memory pipeline in #139, #143, and #144 to SuperNova as well. Since the core logic was already established in the previous Nova PRs, this PR mostly just refactors and cleans up the SuperNova API.
Notes:
- We don't remove the use of `R1CSShape::multiply_vec`, since it's still in `(pp)snark.rs`. The concatenation of `z = W.W ++ U.u ++ U.X` happens anyways, so we can keep the instances of `S.multiply_vec(z)` for readability.

Cleanup memory pipeline for SuperNova

---

.github/workflows/gpu-ci.yml

Based on https://github.com/lurk-lab/lurk-rs/blob/main/.github/workflows/gpu-ci.yml

ci: Add GPU tests on `merge_group`

---

.gitignore
Cargo.toml
benches/compressed-snark.rs
benches/pcs.rs
benches/recursive-snark.rs
src/provider/ipa_pc.rs
src/provider/mlkzg.rs
src/provider/mod.rs
src/provider/non_hiding_zeromorph.rs
src/provider/util/mod.rs
src/spartan/polys/mod.rs
src/spartan/polys/multilinear.rs

The goal of this PR is to implement test vectors & benchmark for PCS.
Implemented two generic test functions that we can use over any `<Engine, EvaluationEngine<Engine>>` for both the correct prove/verify flow and a bad proof verification flow.
This is part of tackling the issue #212

Test vectors & benchmark for PCS

---

Cargo.toml
src/gadgets/nonnative/bignat.rs
src/r1cs/sparse.rs

related: https://github.com/lurk-lab/ci-workflows/issues/10

fix: make sure tests compile on Wasm properly

---

src/provider/ipa_pc.rs
src/provider/mod.rs
src/provider/non_hiding_kzg.rs
src/provider/non_hiding_zeromorph.rs
src/provider/util/fb_msm.rs
src/provider/util/mod.rs
src/spartan/mod.rs
src/spartan/polys/masked_eq.rs
src/spartan/polys/univariate.rs
src/spartan/ppsnark.rs
src/spartan/sumcheck/mod.rs
src/supernova/mod.rs

We've recently introduced quite a few visibility modifiers, here are the ones that are not needed (found through brute force).
The experimental nature of our repo will probably make the next release a major bump, so backwards-compatibility probably isn't the priority.
This will also help with https://github.com/microsoft/Nova/pull/283

fix: remove needless visibility modifiers

---

.github/workflows/gpu-ci.yml
Cargo.toml
src/provider/pasta.rs

This PR deals with the upstream changes in `grumpkin-msm` (https://github.com/lurk-lab/grumpkin-msm/pull/3) that add pasta bindings, causing the removal `pasta-msm`.

Add Grumpkin-Pasta bindings

---

src/digest.rs
src/gadgets/nonnative/bignat.rs
src/lib.rs
src/provider/ipa_pc.rs
src/provider/kzg_commitment.rs
src/provider/pedersen.rs
src/r1cs/util.rs
src/spartan/polys/eq.rs
src/spartan/polys/identity.rs
src/spartan/polys/masked_eq.rs
src/spartan/polys/multilinear.rs
src/spartan/polys/power.rs
src/spartan/polys/univariate.rs
src/supernova/circuit.rs
src/supernova/snark.rs
src/supernova/test.rs
src/traits/circuit.rs

Bounds on structs are generally not preferable (see e.g. [ref](https://stackoverflow.com/questions/49229332/should-trait-bounds-be-duplicated-in-struct-and-impl)), yet they're present in many places in the code base, even on structs which operation is purely parametric in their contents. This is in part because trait bounds on structs are viral (they force any super-structure that reuses the struct to replicate them).
This PR removes some unneeded instances (and should also help w/ Supernova integration where applicable).

Remove uneeded bounds on structs

---

.github/dependabot.yml
.github/workflows/docs.yml
.github/workflows/nightly.yml
.github/workflows/rust.yml

- The pull request introduces predefined GitHub actions for CI env setup from `lurk-lab/ci-workflows` to simplify the existing Rust action workflow,
- A new workflow for generating and deploying crate docs has been added, triggering on push to the `dev` branch and on changes in Rust and Cargo files.
- Updates have been made to the dependabot configuration to enable 'minor' and 'patch' types for rust dependencies.
- Lastly, a new nightly workflow is set up for sanity checks, including jobs to examine unused dependencies and verify rust version.

ci: Refactor GitHub workflows

---

.github/PERF_REGRESSION.md
.github/tables.toml
.github/workflows/gpu-bench.yml
Cargo.toml
benches/common/mod.rs
benches/compressed-snark-supernova.rs
benches/compressed-snark.rs
benches/justfile
benches/recursive-snark-supernova.rs
benches/recursive-snark.rs
build.rs

- Adds a benchmark regression test when merging a PR, based on https://github.com/lurk-lab/lurk-rs/blob/main/.github/workflows/merge-tests.yml
- Refactors the `recursive-snark` benchmark group and ID to enable formatting with `criterion-table`. This will be extended to `compressed-snark` and their supernova counterparts when ready.
- I attempted to test the `criterion-table` output in https://github.com/lurk-lab/arecibo/commit/a621594fa19c6ba89bd93c0bd3772f3f2765c6b2#commitcomment-136557829, and the basic logic works. Unfortunately, we're limited by the fact that the base benchmarks on `dev` don't have the same formatting or parameters as this PR, so it's impossible to demo exactly what it will look like beyond the proposal below.
- It does correctly pick up the artificial regression I …

ci: Add comparative GPU benchmarks on `merge_group`

---

src/lib.rs
src/provider/mlkzg.rs

Fixes https://github.com/lurk-lab/arecibo/issues/228
The obvious solution could be just reducing the number of iteration in [following]((https://github.com/lurk-lab/arecibo/blob/dev/src/provider/mlkzg.rs#L232)) loop to `ell-1` with subsequent pushing `eval` to `polys`. But, as @adr1anh noted in some of discussions we don't need to compute the commitment to this constant polynomial at prover side, since verifier has all necessary information to do that on its side, so in this PR, the `EvaluationArgument` created by prover contains `comms` without commitment to `eval`. It is recomputed at verifier's side and added to `com` vector before executing `kzg_verify_batch`. 
**Important detail**
The following check:
```
if i == ell - 1 && *eval != Pi[0] {
return Err(NovaError::UnSat);
}
```
from …

Optimising proving by avoiding recomputing final `Pi` polynomial in MLKZG

---

Cargo.toml
src/lib.rs
src/supernova/test.rs

- Introduced `halo2curves` version `0.6.0` as a global dependency with additional features
- Eliminated specific target architecture dependency on `halo2curves`
- Testing with an updated `grumpkin-msm` source using a distinct git URL and branch
Companion PR of
- https://github.com/lurk-lab/grumpkin-msm/pull/11
- https://github.com/lurk-lab/lurk-rs/pull/1037

chore: Update halo2curves dependency and adjust grumpkin-msm source

---

.github/workflows/gpu-ci.yml
Cargo.toml

- Removed OpenCL support from GPU testing and respective CI/CD processes
- Revised `gpu-ci.yml` to reflect changes in the GPU testing environment
- Eliminated unnecessary dependencies from main dependencies of `Cargo.toml`
- Moved dependencies `tap`, `tracing-texray`, and `tracing-subscriber` to development dependencies
- Cleaned up formatting in `dev-dependencies` section of `Cargo.toml`

chore: Refactor GPU tests and dependencies, remove OpenCL support

---

.github/workflows/gpu-bench.yml

Fixes bugs similar to those uncovered in https://github.com/lurk-lab/lurk-rs/pull/964, mainly that the regression issue comment would fire regardless of the regression checking step.

ci: Fix GPU merge regression check workflow

---

.github/workflows/gpu-bench.yml
benches/justfile

Based on https://github.com/lurk-lab/lurk-rs/pull/1062

ci: Fix errors

---

src/lib.rs
src/provider/mlkzg.rs
src/provider/mod.rs
src/provider/util/mod.rs
src/spartan/polys/univariate.rs

This is mostly implemented as a proof-of-concept to align with @adr1anh on #223. The RLC implements Horner's scheme on any iterator operand with the correct `MulAssign`, `AddAssign` traits.
- Introduced a new function `rlc`, which implements Horner's scheme,
- Applied traits `Borrow`, `MulAssign`, and `AddAssign` to define it, which exist on `UniPoly`,
- Used `rlc` function in `evaluate` method and `kzg_compute_batch_polynomial`,
- Updated closures in `mlkzg.rs` file to directly handle vector arguments, simplifying the overall operations.
- Streamlined the code by eliminating unnecessary assertions in `kzg_verify_batch` closure and redundant inner function in `kzg_compute_batch_polynomial`.
1. extend the rlc to different parts of the code base, improve ergonomics, etc ... 
- I'd be happy …

refactor: Implement and integrate `rlc` function for simplified lin. combination

---

.github/workflows/gpu-bench.yml
benches/common/mod.rs
benches/common/supernova/targets.rs

- Shortens Criterion benchmark report names to account for the 100 character limit in https://github.com/bheisler/cargo-criterion/blob/main/src/report.rs#L123. Starts with Supernova benches as the others aren't used in CI
- Fixes a missing input to `criterion-table` in the GPU regression check

Shorten benchmark names and fix CI

---

.github/workflows/gpu-bench.yml

- Updated the `JasonEtco/create-an-issue@v2` step to handle existing issues properly.
- Fixes #252

ci: Improve GitHub GPU regression action

---

.github/workflows/gpu-ci.yml

- Fixes a timeout issue due to the inclusion of `debuginfo`, which is solved by using the `release` Cargo profile instead of `dev-ci`
- Activates the `asm` feature to improve performance of Bn256 tests
Successful run: https://github.com/lurk-lab/arecibo/actions/runs/7575501849/job/20632243364?pr=271

ci: Disable debug info for GPU tests

---

rust-toolchain.toml
src/provider/non_hiding_kzg.rs

- Added `#[allow(clippy::map_identity)]` clause to the `verify` function in `src/provider/non_hiding_kzg.rs` to avoid Clippy's interference
- Upgraded the Rust toolchain to version `1.75` in `rust-toolchain.toml`.
- Closes #266

chore: Upgrade rust toolchain

---

examples/and.rs
src/circuit.rs
src/constants.rs
src/gadgets/ecc.rs
src/gadgets/r1cs.rs
src/lib.rs
src/nifs.rs
src/provider/traits.rs
src/r1cs/mod.rs
src/supernova/circuit.rs
src/supernova/test.rs
src/traits/commitment.rs

This ports the following upstream PRs:
- https://github.com/microsoft/Nova/pull/286 (no-op)
- https://github.com/microsoft/Nova/pull/289 (easy)
- https://github.com/microsoft/Nova/pull/290 (trivial)
- https://github.com/microsoft/Nova/pull/291 (non-trivial)
- https://github.com/microsoft/Nova/pull/294 (easy)
The next-to-last one should impact our upstream Supernova PR in minor ways, please review.

Nova forward ports

---

src/provider/non_hiding_kzg.rs

- Added a `batch_commit` method to generate multiple commitments from a list of polynomials.
- Introduced a `batch_open` functionality for evaluating multiple polynomials at different points.
- Implemented `batch_verify` function for validation of polynomial evaluations in a multi-commitment setup.
- Verified the correctness of the batch operations with a new unit test `batch_check_test`.
These basic variants of batch KZG were originally part of #145

feat: Implement batch operations in non_hiding_kzg module

---

Cargo.toml

Adapts to https://github.com/lurk-lab/grumpkin-msm/pull/9, enabling GPU acceleration when the `cuda` feature is enabled

Enable `grumpkin-msm` CUDA feature

---

.cargo/config
src/gadgets/ecc.rs
src/lib.rs
src/provider/poseidon.rs
src/r1cs/sparse.rs
src/spartan/batched.rs
src/spartan/batched_ppsnark.rs
src/spartan/mod.rs
src/spartan/ppsnark.rs
src/spartan/snark.rs
src/supernova/mod.rs
src/supernova/snark.rs
src/traits/mod.rs

Adds missing `Debug` implementations, along with fixing some annoying things I found while working on something else.

refactor: add missing Debug implementations

---

benches/pcs.rs
examples/and.rs
examples/minroot.rs
src/lib.rs
src/provider/hyperkzg.rs
src/provider/mod.rs

This is a port of the portion of the following upstream PRs not already present in the present repo:
- https://github.com/microsoft/Nova/pull/299
- https://github.com/microsoft/Nova/pull/300

Minor MLKZG adjustments (Nova forward ports)

---

Cargo.toml
benches/pcs.rs
examples/minroot.rs
src/lib.rs
src/provider/hyperkzg.rs
src/provider/ipa_pc.rs
src/provider/non_hiding_kzg.rs
src/provider/non_hiding_zeromorph.rs
src/provider/util/mod.rs
src/spartan/batched.rs
src/spartan/batched_ppsnark.rs
src/spartan/ppsnark.rs
src/spartan/snark.rs
src/supernova/mod.rs
src/supernova/snark.rs
src/supernova/test.rs
src/traits/evaluation.rs
src/traits/snark.rs

This PR removes extra copies of the `CommitmentKey` in the `ProverKey` and `VerifierKey`.
Using the results of this PR, we hope to remove the ProverKey and VerifierKey in Lurk's PublicParams, leaving only the nova::PublicParams field there, from which it's cheap to derive the removed fields as needed,
This notices that it is fundamentally cheap to derive prover and verifier key from a set of universal public parameters (in nova parlance, the `CommitmentKey`), and takes that into motion:
- the setup functions for instances of `EvaluationEgine` are deterministic and near-free,
- by composition, so is the setup of `CompressedSNARK`,
- those functions do not need to allocate a significant amount of data,
- we consequently drop the `Serialize`, `Deserialize` and `Abomonate` bounds on all …

refactor: avoid superfluous clones in `ProverKey` and `VerifierKey` for Nova & SuperNova

---

src/errors.rs
src/lib.rs
src/nifs.rs
src/provider/keccak.rs
src/provider/non_hiding_kzg.rs
src/spartan/batched.rs
src/spartan/batched_ppsnark.rs
src/supernova/error.rs
src/supernova/mod.rs
src/supernova/snark.rs

This should help us be more rigorous with cloning. Tested to not break Lurk in the (currently unused) scenario where we'd use pre-processing variants of compressing SNARKs. There will probably be another, slightly more extensive cleanup after #285 merges (as that PR has the downstream effect of shrinking Lurk's requirements on Arecibo, see https://github.com/lurk-lab/lurk-rs/pull/1085).

Remove superfluous instances of derive(Clone) (easy)

---

src/lib.rs
src/provider/hyperkzg.rs
src/provider/non_hiding_kzg.rs
src/provider/non_hiding_zeromorph.rs
src/provider/pedersen.rs
src/r1cs/mod.rs
src/r1cs/sparse.rs
src/spartan/sumcheck/engine.rs
src/supernova/mod.rs
src/traits/evaluation.rs
src/traits/mod.rs
src/traits/snark.rs

Improves rustdoc formatting, fixes one error which is throwing up our CI:
https://github.com/lurk-lab/arecibo/actions/workflows/docs.yml

Fix docs (easy)

---

src/circuit.rs
src/provider/hyperkzg.rs
src/provider/ipa_pc.rs
src/provider/kzg_commitment.rs
src/provider/non_hiding_zeromorph.rs
src/provider/pedersen.rs
src/provider/poseidon.rs
src/supernova/mod.rs

Tested on Lurk. The structs that lose `Deserialize`but not `Serialize` here in general need the later to be `Digestible`

Remove unneeded derive(Serialize, Deserialize) (easy)

---

src/provider/hyperkzg.rs
src/provider/ipa_pc.rs
src/provider/pedersen.rs
src/provider/traits.rs
src/traits/commitment.rs
src/traits/evaluation.rs

This experiments with re-structuring the IPA to:
- avoid implicit or needless `CommitmentKey` clones (I've had to import some changes from #287),
- avoid depending on calling the MSM in `impl CommitmentKeyExtTrait for pedersen::CommitmentKey`, instead relying on an already-available implementation of `Mul<E::Scalar, Output = E> for E::Affine`.
That experiement is largely unsuccessful, since MSM implementation (which resolves to `cpu_best_msm` since the scalar length is 2) is about 5% faster[^1]. We tactically revert to the MSM in that particular line.
<details> 
<summary> I ran the pcs benchmarks (click to unfold) </summary>
```
group                                                                                                                                      dev …
```

Refactor MSM instances in the IPA

---

.github/workflows/bench_pr_comment.yml
benches/bench.env

- Removes old PR comment benches for now while https://github.com/lurk-lab/ci-workflows/issues/15 and other GPU benchmarking actions are centralized and configured in https://github.com/lurk-lab/ci-workflows.
- Adds a GPU benchmark on PR comment action for the short term based on https://github.com/lurk-lab/lurk-rs/blob/main/.github/workflows/bench-pr-comment.yml#L54
- Untested for this repo as the code needs to be on `dev` to trigger properly. However it works well in `lurk-rs`

ci: Add GPU Supernova benchmark on PR comment

---

benches/common/supernova/bench.rs
benches/common/supernova/mod.rs
benches/compressed-snark.rs
benches/compute-digest.rs
benches/recursive-snark.rs
benches/sha256.rs
examples/and.rs
examples/minroot.rs
src/circuit.rs
src/lib.rs
src/provider/mod.rs
src/supernova/circuit.rs
src/supernova/mod.rs
src/supernova/snark.rs
src/supernova/test.rs
src/traits/mod.rs

```rust
E1: Engine<Base = E2::Scalar>,
E2: Engine<Base = E1::Scalar>,
C1: StepCircuit<E1::Scalar>,
C2: StepCircuit<E2::Scalar>,
```
Becomes 
`E1: CurveCycleEquiped`
And 
```rust
E1: Engine<Base = E2::Scalar>,
E2: Engine<Base = E1::Scalar>,
C1: StepCircuit<E1::Scalar>,
C2: StepCircuit<E2::Scalar>,
S1: RelaxedR1CSSNARKTrait<E1>,
S2: RelaxedR1CSSNARKTrait<E2>,
```
becomes
```rust
E1: CurveCycleEquipped
S1: RelaxedR1CSSNARKTrait<E1>,
S2: RelaxedR1CSSNARKTrait<SecEng<E1>>,
```
> [!NOTE]
> Lurk is not expected to compile on top of this, Companion PR at https://github.com/lurk-lab/lurk-rs/pull/1092

Some Type simplifications

---

Cargo.toml
src/provider/bn256_grumpkin.rs
src/provider/non_hiding_kzg.rs
src/provider/pasta.rs
src/provider/pedersen.rs
src/provider/traits.rs

- Added comments in `non_hiding_kzg.rs` and `pedersen.rs` files for explanation of abomonation annotations
- Updated `traits.rs` and `pasta.rs` with compile-time assertions for group data memory representation
- Included a new dependency on `static_assertions` version `1.1.0` in `Cargo.toml`.

refactor: enhance safety of Abomonation annotations

---

src/lib.rs
src/supernova/mod.rs

This PR just adds simple getter methods for recursive SNARKs. (Maybe we should do the same for compressed SNARKs).
The reasoning behind this is that it simplifies Lurk's Prover trait. See [L#1115](https://github.com/lurk-lab/lurk-rs/pull/1115)

IO getters for `RecursiveSnark`

---

.github/workflows/nightly.yml

Uses the typo checker workflow added in https://github.com/lurk-lab/ci-workflows/pull/29, which opens a PR with typo fixes and comments unsolvable typos in the PR description.
I tested the output of `typos --write-changes` locally and it seems to work quite well, no false positives that I could see. If merged, we should get a nice-looking PR on the next morning.

ci: Add nightly typo checker workflow

---

.github/workflows/bench_pr_comment.yml

Uses the reusable workflow from https://github.com/lurk-lab/ci-workflows/pull/38. This replaces the existing `!gpu-benchmark` command with 
`!benchmark`, as shown in the following examples:
```
!benchmark
```
This will run the default benchmark settings, specified in the workflow file of this PR.
Alternatively: 
```
!benchmark --bench supernova-ci --bench pcs --features cuda
ARECIBO_BENCH_NUM_CONS=16384,1048576
```
This will run with each of the input benchmarks, features, and env vars.
> [!IMPORTANT]
> - If you want to benchmark with GPU acceleration enabled, you *must* specify `--features cuda` in the comment body (see above example). Otherwise, the benchmarks will still run on the same GPU-equipped benchmark machine, but will run using the CPU only.
- The previous `!gpu-benchmark` …

ci: Use configurable `!benchmark` PR comment

---

examples/minroot.rs

Browsing through the examples and benches, and found this misleading typo.

minroot: Fix comment typo (easy)

---

src/provider/util/mod.rs
src/r1cs/sparse.rs
src/spartan/batched.rs
src/spartan/batched_ppsnark.rs
src/spartan/mod.rs
src/spartan/polys/eq.rs
src/spartan/polys/identity.rs
src/spartan/polys/power.rs
src/spartan/ppsnark.rs
src/spartan/snark.rs

This is streamlining of the batched snark/ppsnark made on the way to resolving the perf difference found in #281 
Differential bench (with `--features "cuda"`) for this PR reveals high variance 🤷 
|                              | `ref=13ff737`             | `ref=7a5d7bf`                     |
|:-----------------------------|:--------------------------|:--------------------------------- |
| **`Prove-NumCons-6540`**     | `378.03 ms` (✅ **1.00x**) | `384.75 ms` (✅ **1.02x slower**)  |
| **`Verify-NumCons-6540`**    | `29.71 ms` (✅ **1.00x**)  | `29.00 ms` (✅ **1.02x faster**)   |
| **`Prove-NumCons-1038732`**  | `9.42 s` (✅ **1.00x**)    | `9.42 s` (✅ **1.00x slower**)     |
| **`Verify-NumCons-1038732`** | `132.44 ms` (✅ **1.00x**) | `115.03 ms` (✅ **1.15x faster**)  |
| …

Rework batches in ppsnark

---

src/lib.rs

Removes an annoying boilerplate duplication in tests (i.e. `test_ivc_nontrivial_with_compression_with` and `test_ivc_nontrivial_with_spark_compression_with` were nearly the same except for one type parameter).

test: Streamline tests (easy)

---

Cargo.toml
src/r1cs/mod.rs
src/r1cs/util.rs
src/spartan/batched.rs
src/spartan/batched_ppsnark.rs
src/spartan/mod.rs
src/spartan/ppsnark.rs
src/spartan/snark.rs

After #305 (which it includes, so go review there plz)
Refactors Polynomial evaluation instances / witnesses to express the specialized functions in terms of the general ones.
For review: the refactoring of `PolyEvalInstance::batch_diff_size`, which is strict about the size of its arguments and inspects it ,to be the implementation of `PolyEvalInstance::batch`, has revealed the later call sites are *not* rigorous about the size of their arguments, nor do they inspect them.
I've patched call-sites to be compliant with the rigor of `batch_diff_size`, but there's another "looser" variant of this PR that would eliminate `x` from the `PolyEvalInstance`.

Refactor Polyeval{Instance, Witness}

---

Cargo.toml
rust-toolchain.toml
src/lib.rs
src/spartan/sumcheck/mod.rs

- fix a couple of maintenance issues on the repo,
- removes more computation / boilerplate in tests.
Please refer to commit messages.

chore: more Maintenance

---

benches/compressed-snark.rs
src/lib.rs
src/spartan/batched.rs
src/spartan/batched_ppsnark.rs

- The obvious things that should be in the code base on the way to solving a#191,
- This does **not** include a replacement of the `snark::RelaxedR1CSSNark` or `ppsnark::RelaxedR1CSSNark` by their batched variants, just additions,
- This does **not** include tests that compare the I/O of each proof (`snark` vs `batched`, `ppsnark` vs `batched_ppsnark`) very carefully at each stage, that's for later.
- This does include benchmarks that allow us to gain confidence that the performance cost of batching is minimal.
- Incidentally, look at that variance on verification of compressed pre-processing SNARKs 🙀 
|                              | `ref=95714b1`             | `ref=26fd303`                     |
|:-----------------------------|:--------------------------|:-------------------------------- …

Rewire batched SNARK to act as a regular SNARK

---

benches/pcs.rs
src/provider/hyperkzg.rs
src/provider/mod.rs
src/provider/non_hiding_kzg.rs
src/provider/non_hiding_zeromorph.rs
src/provider/shplonk.rs

This PR adds Shplonk-based optimisation to HyperKZG PCS. For simplifying the reviewing process and focusing on correctness at first, It is implemented as a separate PCS (one more implementation of `EvaluationEngineTrait`) and contains most of @adr1anh's suggestions kindly provided in both private discussions and during intermediate reviewing of [draft](https://github.com/lurk-lab/arecibo/tree/shplonk-experiments/src) version.
Once this PR is merged, I'm planning to have some more follow-up PRs to solve https://github.com/lurk-lab/arecibo/issues/302, https://github.com/lurk-lab/arecibo/issues/304 and https://github.com/lurk-lab/arecibo/issues/303.

Initial Shplonk prover/verifier implementation

---

Cargo.toml

Fixes e.g. https://github.com/lurk-lab/arecibo/actions/runs/7902971912/job/21576950128?pr=292
1.71.0 required by Neptune: https://github.com/lurk-lab/neptune/blob/main/Cargo.toml#L9

chore: Update `rust-version`

---

benches/common/supernova/bench.rs
benches/common/supernova/mod.rs
benches/compressed-snark.rs
benches/compute-digest.rs
benches/recursive-snark.rs
benches/sha256.rs

chore: switch benches to hzkg/bn254

---

src/circuit.rs
src/constants.rs
src/gadgets/r1cs.rs
src/lib.rs
src/supernova/circuit.rs
src/supernova/test.rs
src/supernova/utils.rs

This PR resolves #321.
The solution adds a const generic parameter to the two structs, and a new constant that is used in both the Nova and SuperNova augmented circuits where the instances are known to have IO of length 2.

Make `AllocatedR1CSInstance` and `AllocatedRelaxedR1CSInstance` generic in the size of IO

---

Cargo.toml
src/provider/hyperkzg.rs
src/provider/shplonk.rs
src/provider/util/mod.rs
src/spartan/batched.rs
src/spartan/batched_ppsnark.rs
src/spartan/mod.rs
src/spartan/ppsnark.rs
src/spartan/snark.rs

- Optimized performance by introducing parallel scans methods across multiple components, focusing on the `rlc<T, F>` method and the `powers` function.
- Switched from `DoubleEndedIteratorExt` to `IndexedParallelIteratorExt` across several files for iterator processing in parallel, and modified corresponding imports accordingly.
- Left `DoubleEndedIteratorExt` as an option, since it's more efficient on small polynomials,
- Added `rayon-scan` to general dependencies
https://gist.github.com/huitseeker/9094bf6b1c68d83f4c0290e68c6c5beb
Excerpt:
```
Benchmarking PCS-Proving 10/arecibo::provider::hyperkzg::EvaluationEngine<halo2cur
time:   [5.3010 ms 5.3071 ms 5.3111 ms]
change: [-1.9609% -1.7245% -1.5197%] (p = 0.00 < 0.05)
Performance has improved.
Benchmarking PCS-Proving …
```

refactor: Optimize polynomial operations with parallel scan

---

Cargo.toml

After:
- https://github.com/lurk-lab/grumpkin-msm/pull/14
- https://github.com/lurk-lab/neptune/pull/272
Details:
- Updated dependencies in Cargo.toml by switching `pasta_curves` from a git repository to a specific version
- Amended `grumpkin-msm` dependency git repository link
- Removed the `[patch.crates-io]` section for `pasta_curves` due to the above changes.
> [!NOTE]
> CI complaining on repo provenance 100% expected until above dependencies merge.
Fixes #332

chore: Refactor dependencies in Cargo.toml to no longer fork pasta

---

Cargo.toml
README.md
benches/compressed-snark.rs
benches/pcs.rs
benches/recursive-snark.rs
benches/sha256.rs
examples/and.rs
examples/minroot.rs
src/bellpepper/mod.rs
src/bellpepper/r1cs.rs
src/bellpepper/test_shape_cs.rs
src/circuit.rs
src/errors.rs
src/gadgets/ecc.rs
src/lib.rs
src/nifs.rs
src/provider/hyperkzg.rs
src/provider/ipa_pc.rs
src/provider/keccak.rs
src/provider/mod.rs
src/provider/poseidon.rs
src/r1cs/mod.rs
src/supernova/circuit.rs
src/supernova/snark.rs
src/supernova/test.rs

Sources:
- https://github.com/microsoft/Nova/pull/303
- https://github.com/microsoft/Nova/pull/308
- https://github.com/microsoft/Nova/pull/309
Overall:
- QoL improvements in naming,
- stricter testing of R1CS shape during Nova's public parameters setup 
> [!NOTE]
> Companion PR at https://github.com/lurk-lab/lurk-rs/pull/1145

Nova Forward ports (easy)

---

Cargo.toml

Companion PR of https://github.com/lurk-lab/bellpepper/pull/84
- Updated the version of `bellpepper-core` dependency to `0.4.0`.
- Changed the repository source for `bellpepper` and `neptune` dependencies from `lurk-lab` to `huitseeker`.
- Transitioned `neptune` dependency's branch from "dev" to "switch-bellpepper-dependency".
> [!IMPORTANT]
> The CI failure on cargo-deny is expected (on commits pointing at the branch of the above PR).
> To stamp, please wait for the commit pointing:
> -  the bellpepper dependency back to https://github.com/lurk-rs/bellpepper@dev
> - the neptune dependency back to https://github.com/lurk-rs/neptune@dev

chore: Update dependency versions and sources in Cargo.toml

---

examples/hashchain.rs

This forward ports the following PR:
https://github.com/microsoft/Nova/pull/311

add a hashchain example (Nova Forward port)

---

src/spartan/snark.rs

- Imported and implemented `PowPolynomial` into `src/spartan/snark.rs`,
- Simplified and optimized `tau` variable generation using `PowPolynomial`, decreasing the transcript use,
- Adjusted `tau` variable generation method in `prove` and `verify` functions
Fixes #155

refactor: Optimize tau generation with PowPolynomial in snark.rs

---

src/provider/hyperkzg.rs
src/provider/ipa_pc.rs
src/provider/util/mod.rs
src/spartan/sumcheck/engine.rs

- Uses Montgomery-style batch inversion from ff:Field, rather than reimplementing in two places,
- Uses batch normalization for HyperKZG inversions.

Batch inversion & normalization

---

.cargo/config.toml
benches/common/supernova/bench.rs
benches/compressed-snark.rs
benches/recursive-snark.rs
benches/sha256.rs
examples/and.rs
examples/hashchain.rs
examples/minroot.rs
src/bellpepper/mod.rs
src/circuit.rs
src/gadgets/ecc.rs
src/lib.rs
src/nifs.rs
src/provider/hyperkzg.rs
src/provider/shplonk.rs
src/r1cs/mod.rs
src/spartan/ppsnark.rs
src/supernova/circuit.rs
src/supernova/snark.rs
src/supernova/test.rs

An assertion failure on a Result cannot output the useful message of the error.
This removes the systematic pattern of asserting on result states, specially when it comes to tests / benches.
Prohibits them for good measure, using [clippy](https://rust-lang.github.io/rust-clippy/master/index.html#/assertions_on_result_states).

No more assert on result

---

src/constants.rs
src/gadgets/nonnative/bignat.rs

In an attempt to see what would happen to the number of constraints if we changed the parameters `BN_N_LIMBS` and `BN_LIMB_WIDTH`, I found a couple places where the arithmetic inadvertently was dependent on the values being hardcoded as 4 and 64 respectively.
I believe this PR makes the necessary changes to make the codebase general enough to allow for varying these parameters. The expect tests expectedly (:drum: haha) fail when changing these two constants, but everything else passes.

Eliminate hard-coded `BN_N_LIMBS` and `BN_LIMB_WIDTH` dependency.

---

src/circuit.rs
src/gadgets/ecc.rs
src/gadgets/mod.rs
src/gadgets/nonnative/util.rs
src/gadgets/r1cs.rs
src/gadgets/utils.rs
src/lib.rs
src/provider/poseidon.rs
src/r1cs/mod.rs
src/supernova/circuit.rs
src/supernova/test.rs
src/supernova/utils.rs

This does two things:
- tests assumptions of some gadgets that `Field::to_repr()` returns something that translates to lower endian,
- constrains the public exports of the gadgets module to explicitly list out everything we actually use.
This helps the move of gadgets away from arecibo, and will be followed by other PRs to crate::gadgets:
- https://github.com/lurk-lab/bellpepper/issues/56
- https://github.com/lurk-lab/bellpepper-gadgets/issues/43
- https://github.com/lurk-lab/arecibo/issues/324

Small Gadgets refactor

---

src/circuit.rs
src/gadgets/ecc.rs
src/gadgets/mod.rs
src/gadgets/r1cs.rs
src/gadgets/utils.rs
src/supernova/circuit.rs

- Function `conditionally_select_vec` is removed and replaced with `conditionally_select_slice` across multiple files for consistency.
- Duplicate functions `conditionally_select` and `conditionally_select_vec` are removed from various modules.
- Unused import, `itertools::Itertools`, removed from `src/gadgets/utils.rs`.
See https://github.com/lurk-lab/bellpepper/pull/85

Refactor to use bellpepper's new conditional selects

---

src/provider/hyperkzg.rs
src/provider/tests/ipa_pc.rs
src/provider/tests/mod.rs

This PR helps in partial solving of https://github.com/lurk-lab/solidity-verifier/issues/52. 
It adds more accurate representing of `CompressedCommitment` value when using it in Solidity templating. "More accurate" means that Grumpkin point compression is also taken to consideration.
To produce compatible unit test for IPA in Solidity, requires merging https://github.com/lurk-lab/solidity-verifier/pull/63

Refinement in IPA templating

---

src/bellpepper/r1cs.rs
src/r1cs/sparse.rs
src/spartan/batched.rs
src/spartan/mod.rs
src/spartan/snark.rs

Small PR to clean up the sparse matrix API, so that manipulating the rows is clear.

chore: encapsulate sparse API

---

README.md

- Expanded HyperKZG description in README to include Zeromorph and highlight unique support for Supernova.
- Added notification about exclusive availability of Zeromorph implementation in this library, pending integration into official Nova repository.
- Incorporated performance enhancements to the HyperKZG implementation inspired by the BDFG20 (Shplonk) protocol.

docs: Update README with exclusive library features and improvements

---

src/lib.rs
src/nifs.rs
src/spartan/batched.rs
src/spartan/batched_ppsnark.rs
src/supernova/snark.rs

- Added `Clone` trait derivation to enhance cloning capabilities within the codebase.
- Improved duplication of `CompressedSNARK` and `NIFS` structures by integrating `Clone` trait.
- Optimized SNARK computations and funcs handling by cloning `CompressedSNARK` structure.
This is motivated by a companion update to Lurk, where the compression mechanism requires returning a uniform type upon calling `.compress()` on a proof that can be recursive or compressed.
> [!NOTE]
> See use in https://github.com/lurk-lab/lurk-rs/pull/1214

feat: Implement `Clone` trait for various structs

---

src/supernova/snark.rs

- Refactored test functions within the supernova snark module to reduce redundancy.
- Consolidated `test_compression_with` and `test_compression_with_circuit_size_difference_with` functions into a single function.
- Introduced a 'circuit factory' function to generate test circuits.
- Removed `test_nivc_trivial_with_compression_with` method, unified under `test_compression_with`.
- Adjusted individual test cases to conform to new structured changes.

refactor: Refactor Supernova test suite and streamline functions

---

Cargo.toml
rust-toolchain.toml
src/gadgets/nonnative/util.rs
src/gadgets/utils.rs

- Updated Rust toolchain from version `1.78` to `1.79`,
- Added an unused attribute to address potential compilation errors related to unused variables in the `Bit` struct in `nonnative/util.rs`.
- Refactored type constraints for increased readability in `alloc_scalar_as_base` function within `utils.rs`.
Companion PR at https://github.com/lurk-lab/lurk-rs/pull/1252
Fixes #382

chore: Update Rust toolchain
