- src/circuit.rs
- src/gadgets/ecc.rs
- src/lib.rs
- src/nifs.rs
- src/provider/keccak.rs
- src/provider/mod.rs
- src/provider/poseidon.rs
- src/provider/secp_secq.rs
- src/spartan/direct.rs
- src/spartan/mod.rs
- src/spartan/polys/eq.rs
- src/spartan/polys/multilinear.rs
- src/spartan/ppsnark.rs
Backport of https://github.com/microsoft/Nova/pull/199 https://github.com/microsoft/Nova/pull/220
> Backport 220

- .github/workflows/rust.yml
- Enable automatic operation for both push and pull request events on `zeromorph` branch.
> ci: Update Github workflow to include `zeromorph` branch

- .cargo/config
- .github/workflows/rust.yml
- benches/recursive-snark-supernova.rs
- examples/minroot_serde.rs
- examples/signature.rs
- src/bellpepper/test_shape_cs.rs
- src/gadgets/nonnative/bignat.rs
- src/lib.rs
- src/provider/poseidon.rs
- src/spartan/ppsnark.rs
- src/supernova/test.rs
- Added a new .cargo/config file with a custom alias "xclippy" to execute Clippy lints for code quality assurance,
- Fixed code correspondingly when necessary,
- Added xclippy to CI
> ci: Bring clippy standards lurk-rs -> arecibo

- ThirdPartyNotices.txt
- src/provider/non_hiding_kzg.rs
- src/provider/non_hiding_zeromorph.rs
- src/spartan/polys/multilinear.rs
Submitted *as a PR* to test CI, mostly.
> Third party notices

- src/bellpepper/mod.rs
- src/provider/keccak.rs
- src/spartan/polys/eq.rs
- src/spartan/polys/multilinear.rs
- src/spartan/polys/univariate.rs
Add some missing tests, see individual commit.
> test: add missing secp/secq tests

- src/lib.rs
- src/provider/non_hiding_kzg.rs
- src/provider/non_hiding_zeromorph.rs
- sets up a few bounds and scaffolding for the ZM EE trait
- sets up src/lib tests.
> Adapt src/lib tests for ZM

- .clippy.toml
- examples/minroot_serde.rs
- src/bellpepper/shape_cs.rs
- src/bellpepper/test_shape_cs.rs
- src/circuit.rs
- src/digest.rs
- src/gadgets/r1cs.rs
- src/gadgets/utils.rs
- src/lib.rs
- src/nifs.rs
- src/provider/ipa_pc.rs
- src/provider/secp_secq.rs
- src/r1cs/mod.rs
- src/r1cs/sparse.rs
- src/spartan/polys/univariate.rs
- src/spartan/sumcheck.rs
- src/supernova/circuit.rs
- src/supernova/mod.rs
- src/supernova/test.rs
- src/traits/circuit.rs
- src/traits/circuit_supernova.rs
See individual commit messages. Cleanups found while reading the supernova code.
> Simplify map_or expressions, remove clippy override noise, improve doc

- Cargo.toml
- src/bellpepper/r1cs.rs
- src/bellpepper/shape_cs.rs
- src/bellpepper/test_shape_cs.rs
- src/gadgets/utils.rs
- src/nifs.rs
- src/r1cs/mod.rs
- src/spartan/snark.rs
Ports the following from upstream:
- https://github.com/microsoft/Nova/pull/233
- the last 3 adjustment commits of https://github.com/microsoft/Nova/pull/232/commits
> Forward ports from Nova

- src/lib.rs
- src/r1cs/mod.rs
* refactor: r1cs and relaxed r1cs is_sat
* docs: unify description
Ports https://github.com/microsoft/Nova/pull/235
> refactor is_sat and modify comment (Nova forward port)

- src/provider/non_hiding_zeromorph.rs
- src/spartan/polys/multilinear.rs
Make quotient testing in Zeromorph more clear. Contributes to #35 
> [!NOTE]
> Lurk isn't expected to compile when rebased on the ZM branch
> Document Zeromorph quotient function

- README.md
Edit the Readme with "rules of the road" for the fork
> doc: Document the fork's behavior

- Cargo.toml
- src/circuit.rs
- src/gadgets/ecc.rs
- src/gadgets/r1cs.rs
- src/lib.rs
- src/r1cs/mod.rs
- src/supernova/test.rs
ports https://github.com/microsoft/Nova/pull/258
> Curve checks on committed point (Nova Forward port)

- src/supernova/circuit.rs
- src/supernova/test.rs
Companion to #117
Add check that `T` is on the curve in the SuperNova circuit.
> SuperNova: check T is on curve

- src/spartan/polys/multilinear.rs
- Expanded the test suite to include test cases asserting the equivalence of MLP evaluation and partial evaluation functions
- Implemented partial evaluation functionality for MLPs in the `multilinear.rs` file
- Enhanced the clarity of the MLP evaluation process by testing it on partial points.
Test tooling:
- Introduced new functions for generating and evaluating Multilinear Polynomials (MLPs) in the `multilinear.rs` file
- Incorporated the use of `ChaCha20Rng`, `SeedableRng`, `RngCore`, and `CryptoRng` libraries for random number generation pertaining to MLP evaluation
> feat: multilinear polynomial evaluation test

- src/r1cs/mod.rs
- src/spartan/batched_ppsnark.rs
- src/spartan/mod.rs
- src/spartan/ppsnark.rs
- src/supernova/snark.rs
- src/traits/snark.rs
Implements the batched ppsnark
> Batched ppsnark

- src/spartan/batched_ppsnark.rs
This PR adds another Sumcheck instance for checking that W has the correct length.
> SuperNova: Check W size

- src/spartan/batched.rs
- src/spartan/batched_ppsnark.rs
- src/spartan/polys/multilinear.rs
- src/traits/snark.rs
- `zip_with` for `batched_ppsnark`
- Complete comment of `BatchedRelaxedR1CSSNARK`
- Restore Abomonation bounds
- Fix nits in `multilinear.rs`
> SuperNova: Small fixes

- src/spartan/batched.rs
- src/spartan/polys/eq.rs
- src/spartan/polys/multilinear.rs
- src/spartan/ppsnark.rs
- src/spartan/snark.rs
This explores the `FromIterator` trait for a few polys. It's less useful than expected because of the prevalence of `FromParallelIterator`.
> Supernova: Some rewrites

- src/spartan/batched.rs
- src/spartan/batched_ppsnark.rs
- src/spartan/sumcheck.rs
- src/supernova/mod.rs
- src/supernova/snark.rs
- src/traits/snark.rs
Depends on #169, which is its target branch.
> Small fixes

- .github/workflows/rust.yml
Letfovers of #131 and #145 .
Closes #171
> ci: various clean-ups after big merges

- Cargo.toml
- benches/compressed-snark-supernova.rs
- benches/compressed-snark.rs
- benches/compute-digest.rs
- benches/recursive-snark-supernova.rs
- benches/recursive-snark.rs
- benches/sha256.rs
- examples/minroot.rs
- src/lib.rs
Companion Lurk PR at https://github.com/lurk-lab/lurk-rs/pull/957
> Release candidate setup

- src/gadgets/ecc.rs
This PR adds the expected number of constraints and aux variables to the ECC tests.
> Report number of constraints for ECC add and smul

- Cargo.toml
- benches/compressed-snark-supernova.rs
- benches/compressed-snark.rs
- src/lib.rs
- src/supernova/test.rs
Maintenance tasks.
I left a big TODO at #193. This is not expected to compile lurk (which will need [a companion PR upgrading h2c](https://github.com/lurk-lab/lurk-rs/pull/967)).
> More small warts (easy)

- src/r1cs/mod.rs
- src/r1cs/sparse.rs
> Sample random R1CS and satisfying instance/witness

- .github/workflows/rust.yml
- deny.toml
> ci: add a cargo-deny config & CI job

- src/gadgets/ecc.rs
> fix: use expected_test for ECC constraint counts

- src/provider/non_hiding_zeromorph.rs
See #222, the commit_open_prove_verify test is subsumed by the subsequent unit test. @tchataigner was right from the start. 🤦
> chore: remove subsumed test (easy)

- src/gadgets/nonnative/bignat.rs
- src/lib.rs
- src/provider/non_hiding_kzg.rs
- src/provider/non_hiding_zeromorph.rs
Fixes typos that CI mentioned but wasn't able to resolve in #314
> chore: fix typos

- src/spartan/batched.rs
- src/spartan/polys/multilinear.rs
- src/spartan/ppsnark.rs
- src/spartan/snark.rs
- src/supernova/circuit.rs
- src/supernova/utils.rs
Slightly faster evaluations by caching chi coefficients between evaluations.
Fixes #293 .
> (slightly) Faster ML evaluations

- src/spartan/polys/univariate.rs
I remember @storojs72 expressing concerns.
> test: add tests for divide_with_q_and_r

- .github/workflows/bench-pr-comment.yml
> ci: Fix `bench-pr-comment.yml` permissions

- .github/workflows/rust.yml
Companion PR of https://github.com/lurk-lab/ci-workflows/pull/48
> chore: Adapt to `ci-workflows` changes

- .github/workflows/bench-pr-comment.yml
After https://github.com/lurk-lab/ci-workflows/pull/51
> ci: Fix `bench-pr-comment.yml`

- .github/workflows/rust.yml
- benches/compressed-snark.rs
- src/r1cs/sparse.rs
- src/spartan/batched.rs
- src/spartan/polys/power.rs
- src/spartan/ppsnark.rs
- src/spartan/snark.rs
Should help #352 make more sense.
Forward ports:
https://github.com/microsoft/Nova/pull/314
https://github.com/microsoft/Nova/pull/313
> (easy) Nova forward ports + limit unused visibility for unchecked Sparse Matrix functions

- examples/hashchain.rs
- rust-toolchain.toml
- src/gadgets/nonnative/mod.rs
- src/provider/poseidon.rs
- src/provider/tests/mod.rs
- src/provider/util/mod.rs
- src/spartan/math.rs
- src/spartan/polys/multilinear.rs
- src/supernova/mod.rs
- Upgraded the Rust toolchain version.
- clippy
> refactor: Bump toolchain and clean lints
